baseURL: "https://jchgu.rbind.io" 
title: Jiancheng Gu
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Data
          url: data/
          weight: 3 


params:
    description: "PhD Researcher in Migration Studies"
    author: Jiancheng Gu
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","data"]
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jiancheng Gu
          subtitle: "Welcome to my website! I am a PhD Researcher at the
            [Department for Migration and Globalisation,](https://www.donau-uni.ac.at/en/university/faculties/business-globalization/departments/migration-globalization.html)
            [University for Continuing Education – Danube University Krems.](https://www.donau-uni.ac.at/en/)
            I study migration policies and their impact, 
            focusing on the interplay between European and Global Southern countries. 
            My dissertation examines why governments sign agreements about returning irregular migrants, 
            what factors influence the enforcement of return, 
            and how these policies shape future migration patterns.
            My PhD is funded by the Horizon Europe project [Finding Agreement in Return (FAiR).](https://fair-return.org)"
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Jiancheng Gu (Photo©Daniel Novotny)

    socialIcons:
        - name: Email
          url: mailto:jiancheng.gu@donau-uni.ac.at
        - name: CV
          url: cv.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=q4IU8RYAAAAJ
        - name: orcid
          url: https://orcid.org/0009-0002-3033-6472
        - name: GitHub
          url: https://github.com/jchgu
        - name: Twitter
          url: https://twitter.com/jch_gu

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jiancheng Gu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2